# Generated by Django 4.2.13 on 2026-03-06 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_statement', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('bonus_challenge', models.TextField(blank=True)),
                ('evaluation_criteria', models.JSONField(default=dict)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('estimated_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assignments_assignment',
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
                ('verdict', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('criteria_scores', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('bonus_attempted', models.BooleanField(default=False)),
                ('raw_ai_response', models.JSONField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assignments_evaluationresult',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solution_code', models.TextField()),
                ('language', models.CharField(max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
            ],
            options={
                'db_table': 'assignments_submission',
            },
        ),
    ]
