# Generated by Django 6.0.3 on 2026-03-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
    ]
