# Generated by Django 4.2.13 on 2026-03-06 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('role_title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
                ('stipend', models.PositiveIntegerField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True, max_length=500)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('required_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'internships_internship',
                'ordering': ['-created_at'],
            },
        ),
    ]
